// Generated by CoffeeScript 1.12.7
(function() {
  var columns, fullFill, height, npm_opc, strand, stream, width;

  npm_opc = require("./opc_init.js");

  width = npm_opc.width;

  height = npm_opc.height;

  strand = npm_opc.strand;

  columns = npm_opc.columns;

  stream = npm_opc.stream;

  fullFill = function(color, fill) {
    var x, y;
    y = 0;
    while (y < height) {
      x = 0;
      while (x < width) {
        if (Math.random() < fill) {
          columns[x].setPixel(y, color[1], color[0], color[2]);
        } else {
          columns[x].setPixel(y, 0, 0, 0);
        }
        x++;
      }
      y++;
    }
    return stream.writePixels(0, strand.buffer);
  };

  fullFill([232, 33, 124], 1);

  fullFill([232, 33, 124], 1);

  setTimeout(function() {
    fullFill([223, 230, 0], 1);
    return fullFill([223, 230, 0], 1);
  }, 1500);

  setTimeout(function() {
    fullFill([49, 253, 0], 1);
    return fullFill([49, 253, 0], 1);
  }, 3000);

  setTimeout(function() {
    fullFill([93, 225, 255], 1);
    return fullFill([93, 225, 255], 1);
  }, 5000);

  setTimeout(function() {
    fullFill([177, 38, 255], 1);
    return fullFill([177, 38, 255], 1);
  }, 7000);

  setTimeout(function() {
    fullFill([232, 33, 124], 1);
    return fullFill([232, 33, 124], 1);
  }, 7000);

}).call(this);
