// Generated by CoffeeScript 1.12.7
(function() {
  var clear, columns, height, npm_opc, strand, stream, width;

  npm_opc = require("./opc_init.js");

  width = npm_opc.width;

  height = npm_opc.height;

  strand = npm_opc.strand;

  columns = npm_opc.columns;

  stream = npm_opc.stream;

  clear = function() {
    var results, x, y;
    y = 0;
    results = [];
    while (y < height) {
      x = 0;
      while (x < width) {
        columns[x].setPixel(y, 0, 0, 0);
        x++;
      }
      results.push(y++);
    }
    return results;
  };

  module.exports = {
    clear: clear
  };

}).call(this);
